name: Deploy
 version: 2.1 

 jobs:
  build:
    docker:
      - image: circleci/python:3.7.6-stretch-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm install -g serverless
            npm install 
      - deploy: 
          name: Deploy
          context: test
          command: |
            #npm install --save serverless-python-requirements
            sls deploy 
        
        