version: 2.1


jobs:
  build:
    docker:
      - image: circleci/python:3.7.6-stretch-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm install -g serverless
            npm install 
      - deploy: 
          name: Deploy
          command: |
            #npm install --save serverless-python-requirements
            sls deploy 
            
 workflows:
  deploy:
    jobs:
      - deploy: # このjobはfiltersによりmasterブランチ「のみ」で実行される
          context: test # ここで先程作成したcontextのAWS認証情報を指定
          filters:
            branches:
              only:
                - master
        